//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHousing.WinUI.DataSources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Top3EstatesWithMostRentsEntities : DbContext
    {
        public Top3EstatesWithMostRentsEntities()
            : base("name=Top3EstatesWithMostRentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Top3EstatesWithMostRents_Result> Top3EstatesWithMostRents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top3EstatesWithMostRents_Result>("Top3EstatesWithMostRents");
        }
    }
}
